package net.rujel.reusables;

import java.text.FieldPosition;
import java.text.SimpleDateFormat;
import java.util.Date;

import com.webobjects.appserver.*;
import com.webobjects.foundation.NSData;

// Generated by the WOLips Templateengine Plug-in at May 13, 2009 4:09:09 PM
public class Export implements WOActionResults {
	protected WOResponse response;
	protected String filename;
	protected boolean rowOpen = false;
	protected boolean valueOpen = false;
	protected boolean firstValue = true;
    
	public Export(WOResponse aResponse,String fileName) {
		response = aResponse;
		filename = fileName;
		beginFile();
    }

	public Export(WOContext context,String fileName) {
		response = WOApplication.application().createResponseInContext(context);
		filename = fileName;
		beginFile();
    }
    
	public WOResponse response() {
		return response;
	}
	
	public WOResponse generateResponse() {
		endFile();
    	response.setHeader("application/octet-stream","Content-Type");
    	StringBuffer buf = new StringBuffer("attachment; filename=\"");
    	try {
    		SimpleDateFormat sdf = new SimpleDateFormat(
    				(filename == null) ? "yyyyMMdd" : filename);
    		sdf.format(new Date(), buf, new FieldPosition(SimpleDateFormat.YEAR_FIELD));
    	} catch (Exception e) {
    		buf.append(filename);
    	}
    	if(filename.indexOf('.') < 0)
    		buf.append(fileExt());
    	buf.append('"');
		response.setHeader(buf.toString(),"Content-Disposition");
		return response;
	}
	
	public String fileExt() {
		return ".csv";
	}
	
	protected void beginFile() {
		NSData content = response.content();
		if(content == null || content.length() == 0)
			return;
		response.setContent(NSData.EmptyData);
		rowOpen = false;
		valueOpen = false;
		firstValue = true;
	}
	
	protected void endFile() {
		if(valueOpen)
			endValue();
		if(rowOpen)
			endRow();
	}
	
	public void beginRow() {
		if(rowOpen)
			endRow();
		rowOpen = true;
		firstValue = true;
	}
	
	public void endRow() {
		if(valueOpen)
			endValue();
		response.appendContentCharacter('\r');
		rowOpen = false;
	}
	
	public void beginValue() {
		if(!rowOpen)
			beginRow();
		if(valueOpen)
			endValue();
		if(!firstValue)
			response.appendContentCharacter(',');
		response.appendContentCharacter('"');
		valueOpen = true;
	}
	
	public void endValue() {
		if(!valueOpen)
			return;
		response.appendContentCharacter('"');
		valueOpen = false;
		firstValue = false;
	}
	
	protected void appendValue(Object value) {
		if(value == null)
			return;
		String vs = value.toString();
		if(vs == null)
			return;
		vs = vs.replaceAll("\"", "\"\"");
		response.appendContentString(vs);
	}
	
	public void addValue(Object value) {
		beginValue();
		appendValue(value);
		endValue();
	}
}