// ResourceLink.java

/*
 * Copyright (c) 2008, Gennady & Michael Kushnir
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without modification, are
 * permitted provided that the following conditions are met:
 * 
 * 	•	Redistributions of source code must retain the above copyright notice, this
 * 		list of conditions and the following disclaimer.
 * 	•	Redistributions in binary form must reproduce the above copyright notice,
 * 		this list of conditions and the following disclaimer in the documentation
 * 		and/or other materials provided with the distribution.
 * 	•	Neither the name of the RUJEL nor the names of its contributors may be used
 * 		to endorse or promote products derived from this software without specific 
 * 		prior written permission.
 * 		
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
 * SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
 * TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 * BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY
 * WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package net.rujel.reusables;

import com.webobjects.appserver.*;
import com.webobjects.foundation.NSArray;
import com.webobjects.foundation.NSDictionary;

// Generated by the WOLips Templateengine Plug-in at Aug 6, 2008 12:39:04 PM
public class ResourceLink extends ExtDynamicElement {
    
    public ResourceLink(String name, NSDictionary associations,
			WOElement template) {
		super(name, associations, template);
	}

	public void appendToResponse(WOResponse aResponse, WOContext aContext) {
    	String framework = (String)valueForBinding("framework",aContext);
    	String cssLink = (String)valueForBinding("cssLink",aContext);
    	String jsLink = (String)valueForBinding("jsLink",aContext);
    	NSArray languagesList = (NSArray)valueForBinding("languagesList",aContext);
    	WOResourceManager rm = WOApplication.application().resourceManager();
    	WORequest req = aContext.request();
    	if(cssLink != null) {
    		aResponse.appendContentString("<link href=\"");
    		aResponse.appendContentString(rm.urlForResourceNamed(cssLink, framework, languagesList, req));
    		aResponse.appendContentString("\" rel=\"stylesheet\" type=\"text/css\"/>\n");
    	}
    	if(jsLink != null) {
    		aResponse.appendContentString("<script type=\"text/javascript\" language=\"JavaScript\" src=\"");
    		aResponse.appendContentString(rm.urlForResourceNamed(jsLink, framework, languagesList, req));
    		aResponse.appendContentString("\"></script>\n");
    	}
    }
}